# Generated by Django 3.2.6 on 2021-08-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_name',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='name',
            new_name='survey_name',
        ),
    ]
