# Generated by Django 3.2.6 on 2021-08-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0002_auto_20210830_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
    ]
