# Generated by Django 3.2.6 on 2021-08-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0006_alter_question_survey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user',
            new_name='created_by',
        ),
    ]
