# Generated by Django 3.2.6 on 2021-08-30 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0007_rename_user_report_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap.survey'),
        ),
    ]
